// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  APIUrl: 'http//localhost:8080/api/',
  envName: 'qa',
  clientId: 'a1318ddb-83c3-4f10-a2d4-1c561e5289fb', // Test environment
  authority: 'https://login.microsoftonline.com/dcb1eb55-51ee-493c-ad1f-d6fa8e67d47d', // Prod environment. Uncomment to use.
  redirectUri: '/',
  postLogoutRedirectUri: '/'
};
